# Generated by Django 5.1.3 on 2024-11-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_alter_userinfo_create_time_alter_userinfo_depart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, verbose_name='号码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (3, '3级'), (4, '4级'), (5, '5级')], default=1, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '已占用'), (2, '未占用')], default=2, verbose_name='状态')),
            ],
        ),
    ]
