# Generated by Django 5.1.3 on 2024-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0006_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市名')),
                ('count', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='logo')),
            ],
        ),
    ]
